[theme]
base="dark"
primaryColor="#0ea5a6"
backgroundColor="#0f172a"
secondaryBackgroundColor="#1f2937"
textColor="#e5e7eb"
font="sans serif"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[client]
showErrorDetails = true

[runner]
magicEnabled = true
